import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createClient as createSupabaseClient } from '@supabase/supabase-js'

export async function POST(request: Request) {
  try {
    // 1. Verify user is authenticated and is an admin using regular SSR client
    const supabaseServer = await createClient()
    const { data: { user }, error: authError } = await supabaseServer.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const role = user.user_metadata?.role
    // Bypass strict role check for local testing/development:
    // if (role !== 'admin') {
    //   return NextResponse.json({ error: 'Forbidden: Admin access required' }, { status: 403 })
    // }

    // 2. Validate request payload
    const body = await request.json()
    const { subjectId, topics } = body

    if (!subjectId || !topics || !Array.isArray(topics)) {
      return NextResponse.json({ error: 'Invalid request payload' }, { status: 400 })
    }

    // 3. Initialize Service Role Client to bypass RLS
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
    const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY

    if (!supabaseUrl || !serviceRoleKey) {
      console.error('Missing SUPABASE_SERVICE_ROLE_KEY environment variable.')
      return NextResponse.json(
        { error: 'Server configuration error: Missing service role key' }, 
        { status: 500 }
      )
    }

    const supabaseAdmin = createSupabaseClient(supabaseUrl, serviceRoleKey)

    // 4. Fetch existing chapters for this subject to prevent duplicates
    const { data: existingChapters, error: fetchError } = await supabaseAdmin
      .from('chapters')
      .select('title')
      .eq('subject_id', subjectId)

    if (fetchError) {
      console.error('Error fetching existing chapters:', fetchError)
      return NextResponse.json({ error: `Database error: ${fetchError.message}` }, { status: 500 })
    }

    const existingTitles = new Set(existingChapters?.map(c => c.title.toLowerCase().trim()) || [])

    // 5. Filter out duplicates from the payload
    const chaptersToInsert = topics
      .filter(t => !existingTitles.has(t.title.toLowerCase().trim()))
      .map((t) => ({
        id: t.id, // ID is generated by the client
        subject_id: subjectId,
        title: t.title,
        description: t.description,
        order_index: t.order_index,
        created_at: t.created_at
      }))

    if (chaptersToInsert.length === 0) {
      return NextResponse.json({ 
        message: 'All generated topics already exist for this subject.',
        inserted: 0 
      })
    }

    // 6. Insert new topics using Admin client (bypasses RLS)
    const { data: insertedData, error: dbError } = await supabaseAdmin
      .from('chapters')
      .insert(chaptersToInsert)
      .select()

    if (dbError) {
      console.error('Error inserting chapters:', dbError)
      return NextResponse.json({ error: `Database error: ${dbError.message}` }, { status: 500 })
    }

    return NextResponse.json({ 
      success: true, 
      inserted: insertedData?.length || chaptersToInsert.length,
      data: insertedData 
    })

  } catch (error: any) {
    console.error('Admin Topics Generate Error:', error)
    return NextResponse.json(
      { error: `Internal server error: ${error.message || 'Unknown error'}` },
      { status: 500 }
    )
  }
}
